version: "3.7"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000
    environment:
      - NODE_ENV=development
    



    

